pipeline:
  name: caperterra
  identifier: caperterra
  projectIdentifier: CaPer_CI_CD
  orgIdentifier: Jorge_playground
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: jigg_terrainfra
        build: <+input>
  stages:
    - stage:
        name: terraform_plan_apply
        identifier: terraform_plan_apply
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: jigg_terrainfra
                    build:
                      type: branch
                      spec:
                        branch: main
    - stage:
        name: terraapprove
        identifier: terraapprove
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: caper_service
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: caperdev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: caperdevcluster
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  type: Container
                  name: run init
                  identifier: run_init
                  spec:
                    connectorRef: DockerJiggcaper
                    image: hashicorp/terraform:latest
                    command: terraform init
                    shell: Sh
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: account.atdaccluster
                        namespace: default
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                        nodeSelector: {}
                    reports:
                      type: JUnit
                      spec:
                        paths: []
                    outputVariables: []
                    envVariables: {}
                    delegateSelectors:
                      - atdac-main
                  timeout: 10m
              - step:
                  type: Container
                  name: run validate
                  identifier: run_validate
                  spec:
                    connectorRef: DockerJiggcaper
                    image: hashicorp/terraform:latest
                    command: terraform validate
                    shell: Sh
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: account.atdaccluster
                        namespace: default
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                        nodeSelector: {}
                    reports:
                      type: JUnit
                      spec:
                        paths: []
                    outputVariables: []
                    envVariables: {}
                  timeout: 10m
              - step:
                  type: Container
                  name: run planplan
                  identifier: run_planplan
                  spec:
                    connectorRef: DockerJiggcaper
                    image: hashicorp/terraform:latest
                    command: terraform plan -out=tfplan
                    shell: Sh
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: account.atdaccluster
                        namespace: default
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                        nodeSelector: {}
                    reports:
                      type: JUnit
                      spec:
                        paths: []
                    outputVariables: []
                    envVariables: {}
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: approveInfra
                  identifier: approveInfra
                  spec:
                    approvalMessage: "\"Aprobar la aplicación del plan de Terraform en el entorno dev\""
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - _project_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      serviceAccounts:
                        - jiggcaper
                    approverInputs: []
                  timeout: 10m
              - step:
                  type: Container
                  name: run apply
                  identifier: run_apply
                  spec:
                    connectorRef: DockerJiggcaper
                    image: "\thashicorp/terraform:latest"
                    command: terraform apply -auto-approve tfplan
                    shell: Sh
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: account.atdaccluster
                        namespace: default
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                        nodeSelector: {}
                    reports:
                      type: JUnit
                      spec:
                        paths: []
                    outputVariables: []
                    envVariables: {}
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
